name: Generate SVGs

on:
  push:
    paths:
      - 'assets/**'
      - 'generateSVG.py'
      - '.github/workflows/generate-svg.yml'
  schedule:
    - cron: '*/30 * * * *' # Regenerate every 30 mins

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Generate SVGs
        run: python generateSVG.py

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add output/
          git commit -m "Auto-generate SVGs" || echo "No changes to commit"
          git push
